apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-nginx
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: inhwan.jung@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-nginx
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
